name: 🐞 Bug Report
title: '[bug] '
description: Report a bug
labels: ['type: 🐛 bug', 'status: 🧹 needs triage']
assignees:
  - melMass

body:
  - type: markdown
    attributes:
      value: |
        ## Before submiting an issue
        - Make sure to read the README & INSTALL instructions.  
        - Please search for [existing issues](https://github.com/melMass/comfy_mtb/issues?q=is%3Aissue) around your problem before filing a report.
        - Optionally check the `#mtb-nodes` channel on the Banodoco discord:  
          [![](https://dcbadge.vercel.app/api/server/AXhsabmDhn?style=flat)](https://discord.gg/IAXhsabmDhn)

        ### Try using the debug mode to get more info

        If you use the env variable `MTB_DEBUG=true`, debug message from the extension will appear in the terminal.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Add node xxx ...
        2. Connect to xxx ...
        3. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows (Default)
        - Linux
        - Mac
      default: 0
    validations:
      required: true

  - type: dropdown
    id: comfy_mode
    attributes:
      label: Comfy Mode
      description: What flavor of Comfy do you use?
      options:
        - Comfy Portable (embed) (Default)
        - In a custom virtual env (venv, virtualenv, conda...)
        - Google Colab
        - Other (online services, containers etc..)
      default: 0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console output
      description: Paste the console output without backticks
      render: sh

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
